import { Roboto, Archivo } from 'next/font/google';

import Layout from '../components/layout';
import '../styles/globals.css';
// import { Progressbar } from '../components/progressbar';
import Progressbar from 'nextjs-toploader';
import { progressbarOptions } from '../shared/constants';

const roboto = Roboto({
    subsets: ['cyrillic'],
    display: 'swap',
    weight: ['400', '500'],
    variable: '--Roboto'
});

const archivo = Archivo({
    subsets: [],
    weight: ['400', '500', '900'],
    variable: '--Archivo'
});

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js'
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            data-theme="dark"
            style={{ colorScheme: 'dark' }}
            className={`${roboto.variable} ${archivo.variable}`}
        >
            <body>
                <Progressbar {...progressbarOptions} />
                <Layout>{children}</Layout>
            </body>
        </html>
    );
}
