import '../styles/globals.css';

// import NextNprogress from 'nextjs-progressbar';

import Layout from '../components/layout';
import { usePathname } from 'next/navigation';
// import { nextNprogressOptions } from '../shared/constants';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js'
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" data-theme="dark" style={{ colorScheme: 'dark' }}>
            <body>
                <Layout>{children}</Layout>
            </body>
        </html>
    );
}
