on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code  
        uses: actions/checkout@v2

      - name: Cache Dependencies 
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Setup Node 14 
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build 
        run: |
          npm ci
          npm run build
        
      - name: Lint 
        run: npm run lint

      - name: Deploy
        id: deploy-vercel-staging
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          
      - name: End-to-end
        uses: cypress-io/github-action@v2
        with:
          config: baseUrl=${{ steps.deploy-vercel-staging.outputs.preview-url }}