name: Deploy
on: [push]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Cache Dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ github.workspace }}/.next/cache
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

            - name: Setup Node 14
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Setup npm
              run: npm install -g npm

            - name: Setup dotenv
              run: |
                  touch .env
                  echo CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} >> .env
                  echo TOKEN_URL=${{ secrets.TOKEN_URL }} >> .env
                  echo MIDDLE_SECRET=${{ secrets.MIDDLE_SECRET }} >> .env
                  echo MIDDLE_URL=${{ secrets.MIDDLE_URL }} >> .env
                  echo API_URL=${{ secrets.API_URL }} >> .env
                  echo API_VERSION=${{ secrets.API_VERSION }} >> .env

            - name: Setup dependencies
              run: npm ci

            - name: Lint
              run: npm run lint

            - name: Unit testing
              run: npm run test

            - name: Start deployment
              uses: bobheadxi/deployments@v1
              id: deployment
              with:
                  step: start
                  token: ${{ secrets.GITHUB_TOKEN }}
                  env: ${{ fromJSON('["Production", "Preview"]')[github.ref != 'refs/heads/main'] }}

            - name: Deploy to Hasura
              uses: tibotiber/hasura-action@master
              with:
                  args: metadata apply
              env:
                  HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
                  HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
                  HASURA_WORKDIR: hasura

            - name: Deploy to Vercel
              uses: amondnet/vercel-action@v20
              id: deploy-vercel-staging
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-args: ${{ fromJSON('["--prod", ""]')[github.ref != 'refs/heads/main'] }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  scope: ${{ secrets.VERCEL_ORG_ID }}

            - name: End-to-end testing
              uses: cypress-io/github-action@v2
              with:
                  record: true
                  config: baseUrl=${{ steps.deploy-vercel-staging.outputs.preview-url }}
              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: End deployment
              uses: bobheadxi/deployments@v1
              if: always()
              with:
                  step: finish
                  token: ${{ secrets.GITHUB_TOKEN }}
                  status: ${{ job.status }}
                  env: ${{ steps.deployment.outputs.env }}
                  deployment_id: ${{ steps.deployment.outputs.deployment_id }}
